### ISSUE TITLE
Improve Phone aspect

### ISSUE THREAD

**Issue by frasanz** [Ibercivis/EU-CS_platform#604]
- [ ] Add button is cut off #598
- [ ] Only some languages are visible #597
- [ ] Blog pictures do not adjust to the right size within the blogs #596 
- [ ] Teaser displaced #594
- [ ] Forum: Top menu bar doesn't show all the options #593
