### ISSUE TITLE
WEBSITE - Login/Sign Up

### ISSUE THREAD

**Issue by Javier-Gasca** [Ibercivis/EU-CS_platform#607]
- [ ] WEBSITE: Login/Sign Up: Create a button that includes both, "Login and Sign Up" #581
- [ ] WEBSITE - Login/Sign Up: No formatting of the email text #580
- [ ] WEBSITE - Login/Sign Up: Activation link invalid #579
- [ ] WEBSITE - Login/Sign Up: State at the Sign Up page why it is useful to have an account #578

**Comment by Javier-Gasca** [comment]
https://github.com/Ibercivis/EU-CS_platform/issues/581
https://github.com/Ibercivis/EU-CS_platform/issues/580
https://github.com/Ibercivis/EU-CS_platform/issues/579
https://github.com/Ibercivis/EU-CS_platform/issues/578

**Comment by Javier-Gasca** [comment]
WEBSITE: Login/Sign Up: Create a button that includes both, "Login and Sign Up" #581
 WEBSITE - Login/Sign Up: No formatting of the email text #580
 WEBSITE - Login/Sign Up: Activation link invalid #579
 WEBSITE - Login/Sign Up: State at the Sign Up page why it is useful to have an account #578
