### ISSUE TITLE
WEBSITE - Moocs

### ISSUE THREAD

**Issue by Javier-Gasca** [Ibercivis/EU-CS_platform#609]
- [ ] Some kind of guide/order for the courses might be useful #576
- [ ] More information about new training modules #575
- [ ] Change the name to "Courses" #574
