### ISSUE TITLE
WEBSITE - Forum

### ISSUE THREAD

**Issue by Javier-Gasca** [Ibercivis/EU-CS_platform#610]
- [ ] WEBSITE - Forum: Signs from formatting are visible #573
- [ ] WEBSITE - Forum: FAQs should be at the top, so that it's easier to find them #572
- [ ] WEBSITE - Forum: The (sub)topics are not very easy to overview #571
