### ISSUE TITLE
WEBSITE - About

### ISSUE THREAD

**Issue by Javier-Gasca** [Ibercivis/EU-CS_platform#611]
- [ ] WEBSITE - About: Add a "For whom?" section #566
- [ ] WEBSITE - About: Principles are written in English (German version) #565
- [ ] WEBSITE- About: Description of CS & its principles should not be at the end #564
- [ ] WEBSITE - About: Logos should be at the end of the page #563
