### ISSUE TITLE
WEBSITE - Resources

### ISSUE THREAD

**Issue by Javier-Gasca** [Ibercivis/EU-CS_platform#612]
- [ ] WEBSITE - Resources: Assign the resource to only one of the main topics #558
- [ ] WEBSITE - Resources: Add an option to select different languages/themes/resource types at once #557
- [ ] WEBSITE - Resources: Show the options only when the content it's available #556
- [ ] WEBSITE - Resources: Delete the type "Event" from the filter #555
- [ ] WEBSITE - Resources: Unclear filter, too much resource types to choose #554
- [ ] WEBSITE - Resources: Definition of "resources" #553
