### ISSUE TITLE
WEBSITE - Projects

### ISSUE THREAD

**Issue by Javier-Gasca** [Ibercivis/EU-CS_platform#613]
- [ ] WEBSITE - Projects: Search filter shows an "empty option" in some topics #552
- [ ] WEBSITE - Projects: End date and status are not accurate #551
- [ ] WEBSITE - Projects: Add a search filter that shows the countries that use the projects #550
- [ ] WEBSITE - Projects: Differentiate Specific CS Projects and National Platforms #549
- [ ] WEBSITE - Projects: Keyword boxes #548
