### ISSUE TITLE
WEBSITE - First Page

### ISSUE THREAD

**Issue by Javier-Gasca** [Ibercivis/EU-CS_platform#614]
- [ ] WEBSITE - First Page: Titles should follow the same order as the menu bar #547
- [ ] WEBSITE - First page: Titles should stand out more #546
- [ ] WEBSITE - First Page: Desktop version = too much scrolling down #545
- [ ] WEBSITE - First Page: Short description of the menu #541
- [ ] WEBSITE - First Page: Boxes are confusing #540
- [ ] WEBSITE - First Page: Header #538
