### ISSUE TITLE
WEBSITE - General

### ISSUE THREAD

**Issue by Javier-Gasca** [Ibercivis/EU-CS_platform#615]
- [ ] WEBSITE - General: Pictures #537
- [ ] WEBSITE - General: Map of Europe and ongoing projects in each country #536
- [ ] WEBSITE - General: Some parts are not translated, they appear in English. #535
- [ ] WEBSITE - General: When it gets translated, the layout changes and needs improvement #534
- [ ] WEBSITE - General: Targets scientists and project coordinators but not citizens #533
- [ ] WEBSITE - General: Cold design #532
