### ISSUE TITLE
JUNE2020

### ISSUE THREAD

**Issue by Javier-Gasca** [Ibercivis/EU-CS_platform#616]
- [ ] JUNE2020: Candidates/projects match-making #530
- [ ] JUNE2020: Research group profiles #529
- [ ] JUNE2020: Research phases - level of involvement #528
- [ ] JUNE2020: It would be good if the email address field on the login page weren't case-sensitive #527
- [ ] JUNE2020: Country #526
- [ ] JUNE2020: Stars in projects, resources and trainings #525
- [ ] JUNE2020: Add a more advanced search filter that also looks for words in the descriptions of projects and resources #524
- [ ] JUNE2020: Add the possibility to add pictures to each event #523
- [ ] JUNE2020: Add option to filter between online and offline events in the event page #522
